extends: substitution
message: Please use '%s' instead of '%s'
level: error
link: https://github.com/InnerSourceCommons/InnerSourcePatterns/blob/main/meta/innersource-spelling.md
ignorecase: false
# swap maps tokens in form of bad: good
swap:
  'innersource': InnerSource
  '(?i)inner source': InnerSource
  '(?i)inner sourcing': InnerSource
  '(?i)inner sourced': InnerSource
  '(?i)innersourcing': InnerSource
  '(?i)innersourced': InnerSource
