# Are all patterns shown somewhere in the main overview (README)?
name: Overview Complete

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  overviewComplete:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      #   with:
      #     fetch-depth: 0

      # - name: Get changed files
      #   id: changed-files
      #   uses: tj-actions/changed-files@v47

      # - name: Filter markdown files only
      #   run: |
      #     md_files=`find ${{ steps.changed-files.outputs.all_changed_files }} -maxdepth 0 -name "*.md" | tr '\n' ' '`
      #     echo "MARKDOWN_FILES=$md_files" >> $GITHUB_ENV
      #     echo "$md_files"

      - name: Check if all patterns are listed in README.md
        run: |
          README="README.md"

          # Ensure README.md exists
          if [[ ! -f "$README" ]]; then
              echo "Error: $README not found!"
              exit 1
          fi

          missing=0

          for file in patterns/*/*.md; do
              if grep -qF "$file" "$README"; then
                  echo "✔ Found: $file"
              else
                  echo "::error ✘ Missing: $file"
                  missing=$((missing + 1))
              fi
          done

          if [[ $missing -gt 0 ]]; then
              echo "Some files are missing from $README."
              exit 1
          else
              echo "All files are mentioned in $README."
              exit 0
          fi
